### ISSUE TITLE
[Feature Request] Statistical distributions roadmap

### ISSUE THREAD

**Issue by bvenn** [fslaborg/FSharp.Stats#257]
Statistical distributions 

- [x] [bernoulli](https://github.com/fslaborg/FSharp.Stats/blob/developer/src/FSharp.Stats/Distributions/Discrete/Bernoulli.fs)
 - [x] [beta](https://github.com/fslaborg/FSharp.Stats/blob/developer/src/FSharp.Stats/Distributions/Continuous/Beta.fs) 
 - [x] [binomial](https://github.com/fslaborg/FSharp.Stats/blob/developer/src/FSharp.Stats/Distributions/Discrete/Binomial.fs)
 - [ ] Cauchy
 - [x] [chi](https://github.com/fslaborg/FSharp.Stats/blob/developer/src/FSharp.Stats/Distributions/Continuous/Chi.fs)
 - [x] [chi-square](https://github.com/fslaborg/FSharp.Stats/blob/developer/src/FSharp.Stats/Distributions/Continuous/ChiSquared.fs)
 - [x] [exponential](https://github.com/fslaborg/FSharp.Stats/blob/developer/src/FSharp.Stats/Distributions/Continuous/Exponential.fs)
 - [x] [F-distribution](https://github.com/fslaborg/FSharp.Stats/blob/developer/src/FSharp.Stats/Distributions/Continuous/F.fs)
 - [x] [gamma](https://github.com/fslaborg/FSharp.Stats/blob/developer/src/FSharp.Stats/Distributions/Continuous/Gamma.fs)
 - [x] [hypergeometric](https://github.com/fslaborg/FSharp.Stats/blob/developer/src/FSharp.Stats/Distributions/Discrete/Hypergeometric.fs)
 - [ ] Kolmogorov-Smirnov #89 
 - [ ] logistic
 - [x] [lognormal](https://github.com/fslaborg/FSharp.Stats/blob/developer/src/FSharp.Stats/Distributions/Continuous/LogNormal.fs) 
 - [ ] Lorentzian
 - [x] [multivariate normal](https://github.com/fslaborg/FSharp.Stats/blob/developer/src/FSharp.Stats/Distributions/Continuous/MultivariateNormal.fs)
 - [x] [negative binomial](https://github.com/fslaborg/FSharp.Stats/blob/developer/src/FSharp.Stats/Distributions/Discrete/NegativeBinomial.fs) (missing tests #256)
 - [x] [normal](https://github.com/fslaborg/FSharp.Stats/blob/developer/src/FSharp.Stats/Distributions/Continuous/Normal.fs)
 - [x] [Poisson](https://github.com/fslaborg/FSharp.Stats/blob/developer/src/FSharp.Stats/Distributions/Discrete/Poisson.fs)
 - [x] [Student's](https://github.com/fslaborg/FSharp.Stats/blob/developer/src/FSharp.Stats/Distributions/Continuous/StudentT.fs)
 - [ ] Weibull
 - [ ] [studentized range](https://github.com/fslaborg/FSharp.Stats/blob/developer/src/FSharp.Stats/Distributions/Continuous/StudentizedRange.fs) (missing fields)
